# Generated by Django 5.0.3 on 2024-04-02 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField()),
                ('destination', models.CharField(max_length=100)),
                ('plan', models.ImageField(upload_to='img/')),
            ],
        ),
    ]
